# -*- coding: utf-8 -*-
"""Question : The create_python_script function creates a new python script in the current working directory, adds the line of comments to it declared  by the 'comments' variable, and returns the size of the new file. Fill in the gaps to create a script ca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXpo-YHwngZ0Tz4GkpQ9cwG9J89BgJSk

### Question 
The create_python_script function creates a new python script in the current working directory, adds the line of comments to it declared  by the 'comments' variable, and returns the size of the new file. Fill in the gaps to create a script called "program.py".
"""

import os

def create_python_script(filename):
  comments = "# Start of a new Python program"
  with open(filename, 'a+') as f:
    f.write(comments)
    print(f.read())
    filesize = os.path.getsize(filename)
  return(filesize)


print(create_python_script("program.py"))

